server:
    port: 8000

spring:
    application:
        name: Inventory Management System
    datasource:
        url: jdbc:postgresql://localhost:5432/testIMS
        username: postgres
        password: postgre
        driver-class-name: org.postgresql.Driver
    jpa:
        database: postgresql
        show-sql: true
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                format_sql: true
                use_sql_comments: true
    devtools:
        restart:
            exclude: src/main/resources/logs/**

#logging:
#    file:
#        name: src/main/resources/logs/application.log
#    level:
#        jpa: DEBUG
#        org:
#            springframework:
#                security: DEBUG
#            hibernate:
#                type: trace
#                orm.jdbc.bind: trace
